# Generated by Django 5.1 on 2024-08-27 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='workbook.customer'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='workbook.worker'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='workbook.user'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='workbook.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='worker_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='workbook.workerskill'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workbook.reservation'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='workbook.user'),
        ),
        migrations.AlterField(
            model_name='workerskill',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_skills', to='workbook.worker'),
        ),
    ]
