# Generated by Django 5.1 on 2024-08-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='worker_skill',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workerskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workerskill',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='WorkerSkill',
        ),
    ]
