# Generated by Django 5.1 on 2024-08-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0005_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workerskill',
            constraint=models.UniqueConstraint(fields=('worker', 'skill'), name='unique_worker_skill'),
        ),
    ]
