# Generated by Django 5.1 on 2024-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_slot_period',
            field=models.FloatField(blank=True, help_text='Duration of the time slot in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='workerskill',
            name='time_slot_period',
            field=models.FloatField(help_text='Duration of the time slot in minutes'),
        ),
    ]
