# Generated by Django 5.1 on 2024-08-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0006_alter_reservation_time_slot_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_slot_period',
            field=models.IntegerField(blank=True, help_text='Duration of the time slot in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='day_end_time',
            field=models.IntegerField(blank=True, help_text='Duration of the time slot in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='day_start_time',
            field=models.IntegerField(blank=True, help_text='Duration of the time slot in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='workerskill',
            name='time_slot_period',
            field=models.IntegerField(help_text='Duration of the time slot in seconds'),
        ),
    ]
