# Generated by Django 5.1 on 2024-09-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0008_alter_chat_flag_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerskill',
            name='time_slot_period',
            field=models.ImageField(help_text='Duration of the time slot in seconds', upload_to=''),
        ),
    ]
