# Generated by Django 5.1 on 2024-09-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0009_alter_workerskill_time_slot_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerskill',
            name='time_slot_period',
            field=models.IntegerField(help_text='Duration of the time slot in seconds'),
        ),
    ]
