# Generated by Django 5.1 on 2024-09-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0010_alter_workerskill_time_slot_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_date_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
