# Generated by Django 5.1 on 2024-09-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0011_alter_reservation_start_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='group_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
